version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: criskodb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: pass1234
    ports:
      - "5432:5432" 
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=criskodb
      - DJANGO_DB_USER=test
      - DJANGO_DB_PASSWORD=pass1234